@startuml schema

skinparam linetype ortho

entity product {
  * id
  --
  name
  description
  price
  store_id
  category_id
  created_at
  updated_at
}

entity product_inventory {
  * id
  --
  product_id
  stock
  created_at
  updated_at
}

entity category {
  * id
  --
  name
  label
  created_at
  updated_at
}

entity product_category {
  * product_id
  * category_id
  --
  created_at
  updated_at
}

product ||-o{ product_category
product ||--o{ product_inventory
product_category |o--|| category


@enduml